# Generated by Django 5.1.7 on 2025-04-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_abv', models.CharField(max_length=3, verbose_name='Sigla')),
                ('name', models.CharField(max_length=240, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('stock', models.IntegerField()),
                ('value', models.FloatField()),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measure', to='warehouse.measure', verbose_name='Unidade de medida')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='warehouse.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
